### ISSUE TITLE
add build option for files that need to be built on change

### ISSUE THREAD

**Issue by iskandarovBakshi** [hirasso/parcel-plugin-watch-reload#11]
lets say you have folder structure
```
src/
  modules/
    header.html
  index.html
```
you included header.html with posthtml-modules, modules folder files change reloads browser but doesn't builds it

**Comment by hirasso** [comment]
Hi @iskandarovBakshi , if your files need to be built, you should use parcel for that. Parcel has support for multiple entry points:

```
parcel file1.html file2.html file3.js
```
This plugin is meant to be used with files that are not included in your build process (e.g. scriptable files like `.php` files).
