### ISSUE TITLE
[Feature] Reload delay

### ISSUE THREAD

**Issue by zodman** [hirasso/parcel-plugin-watch-reload#7]
Sometimes the backend is not reloaded when parcel is already reloaded.

Plz, add a small reload delay by conf.

**Comment by hirasso** [comment]
Hi @zodman , can you describe your feature request a bit more?

**Comment by zodman** [comment]
Time, in milliseconds, to wait before instructing the browser to reload/inject following a file change event
OR
Execute some command to send a signal to reload the browser.

**Comment by hirasso** [comment]
OK, I will take care of a delay setting. sending the signal manually doesn't work as far as I know, since the parcel hmr is running in a websocket.

**Comment by hirasso** [comment]
Hi @zodman , I introduced [a new setting](https://github.com/hirasso/parcel-plugin-watch-reload#optional-settings) `reloadDelay`. Hope this helps.

**Comment by hirasso** [comment]
So... any news? Did this help?

**Comment by zodman** [comment]
yes! i had using it thanks!
